Environment:
   Region: us-west-2
   Environment: test
   StackName: chromium-lambda-${Environment}-${Region}
   DeploymentBucket: deployment.${Region}
   DeploymentPrefix: ${StackName}
   Profile: default
CloudFormation:
   EnvironmentName: ${Environment}-${Region}

   DependecyLayerName: chromium-lambda-dependencies
   DependecyLayerVersion: 5

   LogRetentionInDays: 7
   DriverFunctionMemorySize: 3008
   DriverFunctionTtlInSeconds: 120
   PdfMergerFunctionMemorySize: 3008
   PdfMergerFunctionTtlInSeconds: 900
Tags:
   Email: jim.gisler@gmail.com
   Application: ${StackName}
   EnvironmentName: ${Environment}-${Region}
